// web-next/app/auth/signin/page.tsx
"use client";
import Signin from "@/components/organisms/Signin";
import { useAuth } from "@/contexts/AuthContext";
import { useRouter } from 'next/navigation'

export default function SigninPage() {
    const { signin } = useAuth();
    const router = useRouter(); 
    const handleSignin = async (data: { email: string; password: string }) => {
        if (!data.email || !data.password) {
            alert('Veuillez remplir tous les champs.');
            return;
        }

        signin(data).then((() => {
            router.push('/boards');
        })).catch((error) => {
            alert('Erreur de connexion : ' + error.message);
        });
    };

    return (
        <Signin onSubmit={handleSignin}></Signin>
    );
}

// web/app/components/organisms/SignIn.vue
<script setup>
import BaseInput from '@/components/atoms/BaseInput.vue';
import Button from '@/components/atoms/Button.vue';

const email = ref('');
const password = ref('');
const emits = defineEmits(['signinSuccess']);

const handleSubmit = () => {
    if (!email.value || !password.value) {
        alert('Veuillez remplir tous les champs.');
        return;
    }

    const authStore = useAuthStore();
    authStore.signin({ email: email.value, password: password.value })
        .then(() => {
            emits('signinSuccess');
        })
        .catch((error) => {
            alert('Erreur de connexion : ' + error.message);
        }); 
};

</script>
<template>
    <div>
        <h2>Me connecter</h2>
        <form @submit.prevent="handleSubmit" class="space-y-4">
            <BaseInput v-model="email" type="email" placeholder="E-mail"></BaseInput>
            <BaseInput v-model="password" type="password" placeholder="Mot de passe"></BaseInput>
            <Button type="submit">Valider</Button>
        </form>
    </div>
</template>
