// web-next/components/organisms/Signin.tsx
'use client';
import React from 'react';
import Input from '../atoms/Input';
import Button from '../atoms/Button';
import { InputType } from '@/enums/Input';
import { ButtonType } from '@/enums/Button';

export default function Signin({ onSubmit }: { onSubmit: (data: { email: string; password: string }) => void }) {
    const [email, setEmail] = React.useState('');
    const [password, setPassword] = React.useState('');

    const handleSubmit = (event: React.FormEvent<HTMLFormElement>) => {
      event.preventDefault(); 
      onSubmit({ email, password });
    };

    return (
        <div className="flex flex-col items-center gap-4 p-6 rounded shadow-md">
            <h2>Hey mais on se connait non ?</h2>
            <p>Connecte toi pour voir tes tableaux !</p>
            <form onSubmit={handleSubmit} className="flex flex-col gap-4 max-w-md">
                <div className="flex flex-col">
                    <label htmlFor="email" className="mb-1 font-medium">Email</label>
                    <Input type={InputType.EMAIL} value={email} onChange={(e) => setEmail(e.target.value)} />
                </div>
                <div className="flex flex-col">
                    <label htmlFor="password" className="mb-1 font-medium">Mot de passe</label>
                    <Input type={InputType.PASSWORD} value={password} onChange={(e) => setPassword(e.target.value)} />
                </div>
                <Button type={ButtonType.SUBMIT}>
                    Se connecter
                </Button>
            </form>
        </div>
    )
}

// web/app/components/organisms/SignIn.vue
<script setup lang="ts">
import BaseInput from '@/components/atoms/BaseInput.vue';
import Button from '@/components/atoms/Button.vue';
import Card from '@/components/molecules/Card.vue';

const email = ref('');
const password = ref('');
const emits = defineEmits(['signinSuccess']);

const handleSubmit = () => {
    if (!email.value || !password.value) {
        alert('Veuillez remplir tous les champs.');
        return;
    }

    const authStore = useAuthStore();
    authStore.signin({ email: email.value, password: password.value })
        .then(() => {
            emits('signinSuccess');
        })
        .catch((error) => {
            alert('Erreur de connexion : ' + error.message);
        }); 
};

</script>
<template>
    <Card class="flex flex-col flex-1 lg:grid gap-x-8 gap-y-4 p-4 sm:p-6">
         <template #heading>
            Hey mais on se connait non ?
        </template>
        <template #subHeading>
            Connecte toi donc !
        </template>
        <form @submit.prevent="handleSubmit" class="flex flex-col gap-2">
            <BaseInput v-model="email" type="email" placeholder="E-mail"></BaseInput>
            <BaseInput v-model="password" type="password" placeholder="Mot de passe"></BaseInput>
            <Button type="submit">Valider</Button>
        </form>
    </Card>
</template>
