// web/app/components/atoms/Select.vue
<script setup>
const props = defineProps({
    options: { type: Array, required: true },
    modelValue: { type: [String, Number, Object], default: null }
})

const emit = defineEmits(["update:modelValue"])

const onChange = (event) => {
  emit("update:modelValue", event.target.value)
}
</script>
<template>
    <select class="border rounded px-3 py-2" :value="modelValue" @change="onChange">
        <option value="" disabled>Sélectionnez...</option>
        <option v-for="option in options" :key="option" :value="option">
            {{ option }}
        </option>
    </select>
</template>

// web-next/components/atoms/Select.tsx
type SelectProps = {
  options: { value: string; label: string }[];
  value: string;
  onChange: (value: string) => void;
};

export default function Select({ options, value, onChange }: SelectProps) {

    const optionsList = options.map((option) => (
        <option key={option.value} value={option.value}>
            {option.label}
        </option>
    ));

    return (
        <select
            className="border border-gray-300 rounded px-3 py-2 focus:outline-none focus:ring-2 focus:ring-blue-500"
            value={value}
            onChange={(e) => onChange(e.target.value)}
        >
            {optionsList}
        </select>
    );
}
