// web/app/components/organisms/AppHeader.vue
<script setup>
import Button from '@/components/atoms/Button.vue';

const usersStore = useUsersStore();
const isAuthenticated = computed(() => usersStore.isAuthenticated);
const authStore = useAuthStore();
const handleSignout = async () => {
    await authStore.signout();
    await usersStore.fetchUser();
};
</script>

<template>
    <header class="bg-gray-800 text-white p-4 flex justify-between items-center">
        <h1 class="text-2xl">Trelol</h1>
        <div>
            <template v-if="isAuthenticated">
                <Button @click="handleSignout">Se deconnecter</Button>
            </template>
            <template v-else>
                <NuxtLink to="/auth/signin" class="mr-4"><Button>Se connecter</Button></NuxtLink>
                <NuxtLink to="/auth/signup"><Button>S'inscrire</Button></NuxtLink>
            </template>
        </div>
    </header>
</template>

// web-next/components/organisms/AppHeader.tsx

'use client';
import { useAuth } from "@/contexts/AuthContext";
import Link from "next/link";
import Button from "@/components/atoms/Button";

export default function AppHeader() {
    const { user, signout } = useAuth();
    const isAuthenticated = !!user;
    const handleSignout = () => {
        signout();
    }
    return (
        <header className="bg-gray-800 text-white p-4 flex justify-between items-center">
            <Link href="/">
                <h1 className="text-2xl font-bold">Trelol</h1>
            </Link>
            <div>
                { isAuthenticated ? (
                    <Button onClick={handleSignout}>Se deconnecter</Button>
                ) : (
                    <div>
                        <Link href="/auth/signin">
                            <Button>Se connecter</Button>
                        </Link>
                        <Link href="/auth/signup" className="ml-4">
                            <Button>S&apos;inscrire</Button>
                        </Link>         
                    </div>
                )
            }
            </div>
        </header>
    );
}
